### ISSUE TITLE
Brew message: Calling Formula.sha1 is disabled! Use Formula.sha256 instead.

### ISSUE THREAD

**Issue by tonylangley** [Gui13/homebrew-linphone#2]
Hi,

I received the following errors:

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/antlr3.2.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/antlr3.2.rb:8:in '<class:Antlr32>'
Please report this to the gui13/linphone tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/gtk-mac-integration.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/gtk-mac-integration.rb:6:in '<class:GtkMacIntegration>'
Please report this to the gui13/linphone tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/libantlr3.4c.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/gui13/homebrew-linphone/libantlr3.4c.rb:9:in '<class:Libantlr34c>'
Please report this to the gui13/linphone tap!
Error: Cannot tap gui13/linphone: invalid syntax in tap!

Hope you can help!

Cheers,
Tony

**Comment by Gui13** [comment]
Hi tony, there's an up to date fork of this home-brew repo here: https://github.com/carsonbaker/homebrew-linphone

He corrected some of the issues, including the SHA1 depreciation. I'm not in contact with him but you could tap his repo instead of you want up-to-date formulas. I don't spend much time maintaining this repo anymore.

@carsonbaker, if you happen to come here, I'd be glad to merge back your changes.
